### PR TITLE
Clear facet, closes #58

### LINKED ISSUE #58: Add clear functionality to POP filters

### PR DESCRIPTION
**Pull request by lauraluiz**
This would do the trick.
@schleichardt @peter-gerhard please review.

### CODE REVIEW

**Comment by schleichardt** [comment]
:+1:

**Comment by peter-gerhard** [comment]
:+1:

**Comment by schleichardt** [comment]
Cool, right now you could click the merge button. My PRs need manual work.

**Comment by lauraluiz** [comment]
Yay! Less work :)

**Pull request merged**
