### PR TITLE
Add additional Title for pop - Connects #73

### PR DESCRIPTION
**Pull request by peter-gerhard**
@lauraluiz @schleichardt
I added a different title for both actions rendering the pop.
1. If you access the pop via category the additionalTitle should be the translated category name
2. If you enter by search it should be 'Serach: "searchTerm" '

### CODE REVIEW

**Comment by schleichardt** [comment]
So do we support German or not? It is weird on the one hand we add translations to the message files on the other hand we hardcode English in classes.

**Comment by peter-gerhard** [comment]
Are you referring to Search? 
So far we don't support it in the url so its '/en/search/:searchTerm', so i didn't bother to do so in the title.
I can add a translation though

**Comment by lauraluiz** [comment]
:+1:

**Comment by schleichardt** [comment]
:+1:

**Pull request merged**
