### PR TITLE
Fix trailing slash problem - Connects #25

### PR DESCRIPTION
**Pull request by peter-gerhard**
@lauraluiz @schleichardt
I added a 301 redirect for urls with trailing slash to their pendants without trailing slash
and removed the trailing slash from the existing routes.
In the future please make sure not to put trailing slashes on routes, otherwise you will not be able to access them

### CODE REVIEW

**Comment by schleichardt** [comment]
:+1: 

In most projects I saw this at the button, but at the top it makes sure we don't use trailing slashes.

**Comment by lauraluiz** [comment]
:+1:

**Comment by lauraluiz** [comment]
*bottom ;)

**Comment by schleichardt** [comment]
fixed ;)

**Pull request merged**
