### PR TITLE
Use sizes for PDP, closes #63

### LINKED ISSUE #63: Select size on PDP and add to cart

### PR DESCRIPTION
**Pull request by lauraluiz**
Please @schleichardt @peter-gerhard review

### CODE REVIEW

**Comment by schleichardt** [comment]
Ok, but fixing the tests might cost much time.

**Comment by lauraluiz** [comment]
Fixed. I was too happy to think about the tests ;)

**Comment by lauraluiz** [comment]
By the way, thanks to changing to a `NamedAttributeAccessor` I found a bug. We were not accessing the LEnumSet correctly.

**Comment by schleichardt** [comment]
@lauraluiz can you please report the bug to the JVM SDK?

**Comment by lauraluiz** [comment]
No, the bug was in Sunrise. The JVM SDK is okay :D

**Comment by schleichardt** [comment]
:relieved:

**Comment by peter-gerhard** [comment]
:+1:

**Comment by schleichardt** [comment]
:+1:

**Pull request merged**
