### PR TITLE
Cart discounts

### PR DESCRIPTION
**Pull request by peter-gerhard**
@schleichardt @lauraluiz 
I removed that cart discounts are applied per line item in order to calculate and show them in ui
for me it doesnt make sense to have the cart discount already applied to the subtotal, whats your opinion on that?

### CODE REVIEW

**Comment by peter-gerhard** [comment]
trang gave her ok for this version at least for dmexco.

**Comment by lauraluiz** [comment]
:+1:

**Comment by schleichardt** [comment]
I am not convinced.

**Comment by schleichardt** [comment]
@peter-gerhard  Can you give me an example how to reproduce and have a look at it?

**Comment by schleichardt** [comment]
ok, had a call with Laura

:+1:

**Pull request merged**
